### ISSUE TITLE
Feature request: Support vhost

### ISSUE THREAD

**Issue by hobofan** [Geal/lapin#19]
CloudAMQP and similar hosted versions of RabbitMQ use a `vhost` for multi-tenant environments.

When trying out lapin, I think the lack of `vhost` support was the only thing "technically" keeping me from establishing a connection.

**Comment by Geal** [comment]
this should work now I'll push a new version soon :)

**Comment by hobofan** [comment]
Just tested it, and its working great! 🎉  Thanks for the quick response @Geal & @Keruspe ! 👍
