### ISSUE TITLE
Fails to connect 2

### ISSUE THREAD

**Issue by dfaust** [Geal/lapin#30]
The future returned by `lapin::client::Client::connect` doesn't always complete.

This is very similar to #28, but I think it might be a different bug.

log file 1: https://www.dropbox.com/s/bhhbxmwx1lm5kk3/a_log.html?dl=0
log file 2: https://www.dropbox.com/s/xyat551tmos6du6/b_log.html?dl=0

**Comment by michaelklishin** [comment]
Can you please take a [Wireshark traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) when that happens?

**Comment by Geal** [comment]
I think it is the same bug, happening in the connector future ( https://github.com/Geal/lapin/blob/master/futures/src/transport.rs#L192-L249 ) but at different steps of the handshake. From what I see, the client receive the `Tune` frame, decodes it but does not interpret it.
I know I need to refactor it, but in the meantime, could you try to run your tests with a version of the lib where there are logs everywhere in that function?
I can try to make a fix on wednesday.

**Comment by dfaust** [comment]
Here is the wireshark log (first time I used wireshark):

https://gist.github.com/dfaust/6bdadbdb6ca6ea38985e8d20946bde60

> the client receive the Tune frame, decodes it but does not interpret it

That seems to be correct.

> could you try to run your tests with a version of the lib where there are logs everywhere in that function?

Sure.

> I can try to make a fix on wednesday

That sounds awesome!

**Comment by dfaust** [comment]
Here is the wireshark log (first time I used wireshark):

https://gist.github.com/dfaust/6bdadbdb6ca6ea38985e8d20946bde60

> the client receive the Tune frame, decodes it but does not interpret it

That seems to be correct.

> could you try to run your tests with a version of the lib where there are logs everywhere in that function?

Sure.

> I can try to make a fix on wednesday

That sounds awesome!

**Comment by dfaust** [comment]
Log file created with https://github.com/dfaust/lapin/blob/pull-31/futures/src/transport.rs#L199-L259 (pull request #31 + some extra logging):

https://www.dropbox.com/s/x86raucn3ukqv9f/log_30_31.html?dl=0

**Comment by Geal** [comment]
so, with #31 and 9dd1e5165b92338074adfde39b52322dbcad6f1a I think the connection bug is fixed. I was able to reproduce by launching an example over and over again until it blocked, and now it does not block anymore for me.
@dfaust can you confirm?

**Comment by dfaust** [comment]
@Geal, I just ran my tests tree times without any failures. So I would say it's fixed.
Thank you! 🎉

**Comment by Geal** [comment]
awesome!

**Comment by whitfin** [comment]
@Geal I'm also seeing this now; using the examples provided I can see the socket coming back from `TcpStream::connect` but it never calls the `and_then` after `Client::connect`. Any ideas? I'm pretty new to Rust but will assist any way I can.
