### ISSUE TITLE
Example consumer code fails to get message

### ISSUE THREAD

**Issue by dobrite** [Geal/lapin#35]
The "consumer" example code in `lapin-futures` gets to "got consumer stream", but then fails to get to the "got message" portion. There are messages in the queue and I see the consumer is connected in Rabbit's web interface. It does move the message from "ready" to "unacked" but never actually gets the message. I also see that that doc test is also `ignore`ed.

I am using `master`.

Any assistance is appreciated. It also could be something with my setup.

**Comment by dobrite** [comment]
FWIW I was able to get messages using `rust-amqp` so I think that rules out my setup.

**Comment by Keruspe** [comment]
Can you paste the output with RUST_LOG=debug ?

**Comment by Geal** [comment]
with RUST_LOG=trace, even :)
Don't worry about the doc test being ignored. If it wasn't, it would fail for anyone that does not have an AMQP server running locally, like docs.rs. We run the tests with the consumer on every commit, too.
I'm not denying there's a bug, though :)

**Comment by dobrite** [comment]
Attached is a `trace` level log from running the following (assumes the "hello" queue already exists):

```rust
#[macro_use]
extern crate log;
extern crate amq_protocol;
extern crate futures;
extern crate tokio_core;
extern crate lapin_futures as lapin;
extern crate env_logger;

use amq_protocol::types::FieldTable;
use futures::Stream;
use futures::future::Future;
use tokio_core::reactor::Core;
use tokio_core::net::TcpStream;
use lapin::client::ConnectionOptions;
use lapin::channel::{BasicConsumeOptions, BasicProperties, BasicPublishOptions,
                     QueueDeclareOptions};

fn main() {
    env_logger::init().unwrap();

    // create the reactor
    let mut core = Core::new().unwrap();
    let handle = core.handle();
    let addr = "127.0.0.1:5672".parse().unwrap();

    let future = TcpStream::connect(&addr, &handle)
        .and_then(|stream| lapin::client::Client::connect(stream, &ConnectionOptions::default()))
        .and_then(|client| client.create_channel())
        .and_then(|channel| {
            channel.basic_publish("hello",
                                  b"hello!",
                                  &BasicPublishOptions::default(),
                                  BasicProperties::default());
            let ch = channel.clone();
            channel
                .basic_consume("hello", "rabbit-pubsub", &BasicConsumeOptions::default())
                .and_then(|stream| {
                    info!("got consumer stream");
                    stream.for_each(move |message| {
                                        debug!("got message: {:?}", message);
                                        info!("decoded message: {:?}",
                                              std::str::from_utf8(&message.data).unwrap());
                                        ch.basic_ack(message.delivery_tag);
                                        Ok(())
                                    })
                })
        });

    core.run(future).unwrap();
}
```

https://gist.github.com/dobrite/e37105352b13325599b3a381ce5ee607

Thank you for looking at this!

**Comment by Keruspe** [comment]
"assumes the "hello" queue already exists"

That's your problem.

The RabbitMQ specs don't error out if you try to do what you're doing, but you won't be able to handle the messages in a channel that hasn't used queue_declare beforehand.

If you queue_declare.and_then(basic_consume) it should work as expected.

Issue #32 is here so that we'll enforce that in future versions

**Comment by dobrite** [comment]
Well that is surprising! Thanks you for the assistance. Now I'm off and running.

**Comment by michaelklishin** [comment]
@Keruspe I'd like to clarify what you are saying above. Yes, in many cases consumers declare the queues they will consume from. However, it is perfectly possible to consume from a queue that already exists without declaring it first. The protocol also has a fairly obscure way of checking if a queue exists called passive declare: it does nothing if the target exists but will throw a channel exception if it does not.

Just to clarify :)
